# Generated by Django 3.2.16 on 2022-12-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221218_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Подтверждение Email', 'verbose_name_plural': 'Подтверждения Email'},
        ),
    ]
